### PR TITLE
Added auth login error handler via Promise.reject()

### PR DESCRIPTION
**Pull request by joseluisq**
Added support for handing auth errors `Spotify.login()` and close auth window via `Promise.reject()`
Example:

```js
Spotify.login().then(function(data) {
  console.log(" deferred.resolve() ")
}, function() {
  console.log(" deferred.reject() ")
});
```

`callback.html`

```html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title></title>
  <script type='text/javascript'>//<![CDATA[
    window.onload = function() {
      var hash = window.location.hash;
      
      // If exists some Spotify error via query string
      if (window.location.search.substring(1).indexOf("error") !== -1) {
        window.close();
      } else {
        if (hash) {
          var token = window.location.hash.split('&')[0].split('=')[1];
          // target.postMessage(token, 'http://example.com/');
          localStorage.setItem('spotify-token', token);
        }
      }
    };
  //]]>
  </script>
</head>
<body>
</body>
</html>

```

### CODE REVIEW

**Comment by eddiemoore** [comment]
@joseluisq Can you get the build to pass first? Then I can review.

**Comment by joseluisq** [comment]
Sorry I had no time for fix it, but I saw that you added the code what I send

**Comment by eddiemoore** [comment]
yeah all fixed now.

**Comment by joseluisq** [comment]
https://github.com/eddiemoore/angular-spotify/commit/76cb71f3085684e60c67885b3c581f0ceff4d301
Great :+1:

**Pull request closed without merging**
